Created End to End service for Voter and added flyway for DB migration
Fallen007/National-Polling-System pull request #3
Opened 2021-09-19 18:10 UTC by Fallen007

1. Added DTO, Controller, Service for Voters
2. Added custom exceptions and their handler
3. Added new maven dependencies
4. Added MapStructMapper interface with methods to do the conversion between DTO and Entity of Voter
5. Added flyway DB migration and created SQL script for initial tables creation

2021-09-19 19:45 UTC, samwho requested changes
It's a good starting point, but I feel like there are parts that can be improved upon. Let me know what you think. You're allowed to disagree with the points I'm raising, don't feel like you have to blindly accept the things I'm saying. :)

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/controller/VoterController.java
> +        voterService.getAllVoters().forEach(voter -> votersList.add(mapper.voterToVoterDto(voter)));
I think it might be possible to use Streams here, something like:

```java
return ResponseEntity.ok(
  voterService.getAllVoters()
    .stream()
    .map(mapper.voterToVoterDto)
    .collect());
```

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/controller/VoterController.java
> +        return ResponseEntity.ok(voterDTO);
```java
return ResponseEntity.ok(
  voterService.getVoterById(voterId)
    .map(mapper.voterToVoterDto)
    .orElseGet(() -> new VoterDTO()));
```

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +    }
I would argue these are both unnecessary.

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            voter = voterRepository.save(voter);
I'd recommend getting in to the habit of always having { braces } around your code blocks, even if they're not necessary. Are you familiar with https://gotofail.com/?

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            throw new ResourceNotFoundException(message);
```suggestion
            throw new ResourceNotFoundException("Voter with ViterID: " + voterId + " does not exist");
```

Shorter, less visual noise.

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +        //checking if voter with given voterId already exists or not
This comment isn't necessary. It's clear from the code what's going on.

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +        //checking if voter with given voterId already exists or not
This comment isn't necessary. It's clear from the code what's going on.

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +        //checking if given email already exits in the records
This comment isn't necessary. It's clear from the code what's going on.

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +        else if(checkIfEmailAlreadyExists(email).equals(true)){
You could get rid of one of these checks by doing:

```java
Optional<Voter> existingVoter = getVoterById(voterId);
if (existingVoter.isPresent() && !existingVoter.get().getEmail().equals(email)) {
  throw new ConflictWithExistingRecordException("The email " + email + " already exists and cannot be used again");
}
```

From this point on you know the voter either doesn't exist, or is the same as an existing voter, so you safely save the record with no further checks.

2021-09-19 19:45 UTC, samwho commented on src/main/resources/db/migration/V1__Initial_Table_Creation.sql
> +--administrators table creation
Does Spring/Flyway generate these migrations for you?

2021-09-19 19:45 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            throw new ResourceNotFoundException(message);
It seems odd to return an `Optional` that will never be empty.

2021-09-20 17:30 UTC, Fallen007 commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            throw new ResourceNotFoundException(message);
Can't help it, the findById method provided by Spring Data JPA returns an Optional

2021-09-20 17:31 UTC, Fallen007 commented on src/main/resources/db/migration/V1__Initial_Table_Creation.sql
> +--administrators table creation
Nope, these were written by me

2021-09-21 09:46 UTC, samwho commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            throw new ResourceNotFoundException(message);
So you can't just return a `Voter` here? In that case, do you need the exception for when the `Voter` isn't found? If the person calling the function is getting an `Optional<Voter>`, the API is suggesting to them that the `Optional` could be empty, so they're obliged to check.

2021-09-21 10:00 UTC, Fallen007 commented on src/main/java/com/national/polling/system/service/VoterServiceImpl.java
> +            throw new ResourceNotFoundException(message);
Okay, I'm getting what you are trying to say here. I'll just return a Voter after checking that the Optional isn't empty.

2021-09-21 10:28 UTC, merged